/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gov.edu.anm.presenter.view;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JFrame;

/**
 *
 * @author luizh
 */
public class presenterGui extends javax.swing.JFrame {

    /**
     * Creates new form Sistema
     */
    public presenterGui() {
        initComponents();

        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        Dimension abasPreferredSize = new Dimension(1400, 730);
        abas.setPreferredSize(abasPreferredSize);
        Dimension menuBarPreferredSize = new Dimension(260, 50);
        menuBar.setPreferredSize(menuBarPreferredSize);
        Dimension tabelaDimension = new Dimension(1100, 402);
        alunosTabelaPanel.setPreferredSize(tabelaDimension);
        alunosTabelaPanel.setMinimumSize(tabelaDimension);

        //Menu configs
        menuBar.setVisible(false);
        menuBar.setEnabled(false);
        menuRightPanel.setVisible(false);
        menuRightPanel.setEnabled(false);
        
        redCircleLabel.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        programBar = new javax.swing.JPanel();
        titleBarSpaceLabel = new javax.swing.JLabel();
        minemizeLabel = new javax.swing.JLabel();
        closeLabel = new javax.swing.JLabel();
        titleBar = new javax.swing.JPanel();
        menuIcon = new javax.swing.JLabel();
        multimeiosLabel = new javax.swing.JLabel();
        mainbarSpaceLabel = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        abas = new javax.swing.JTabbedPane();
        abaEquipes = new javax.swing.JPanel();
        alunoCadastro = new javax.swing.JPanel();
        alunosNomeLabel = new javax.swing.JLabel();
        alunosNomeTextField = new javax.swing.JTextField();
        alunosNomeLabel1 = new javax.swing.JLabel();
        alunosNomeTextField1 = new javax.swing.JTextField();
        alunosTurmaLabel = new javax.swing.JLabel();
        alunosTurmaComboBox = new javax.swing.JComboBox<>();
        alunosNovoBotao = new javax.swing.JLabel();
        alunosSalvarBotao = new javax.swing.JLabel();
        alunosEditarBotao = new javax.swing.JLabel();
        alunosExcluirBotao = new javax.swing.JLabel();
        alunosNomeLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        alunosNomeTextField2 = new javax.swing.JTextField();
        alunosNovoBotao1 = new javax.swing.JLabel();
        alunosDivideBar = new javax.swing.JPanel();
        alunosPesquisaPanel = new javax.swing.JPanel();
        alunosPesquisaBar = new javax.swing.JPanel();
        alunosPesquisaLabel = new javax.swing.JLabel();
        alunosPesquisaTextField = new javax.swing.JTextField();
        alunosPorLabel = new javax.swing.JLabel();
        alunosPorComboBox = new javax.swing.JComboBox<>();
        alunosTabelaPanel = new javax.swing.JPanel();
        alunosTabelaContent = new javax.swing.JScrollPane();
        alunosTabela = new javax.swing.JTable();
        abaTemporizador = new javax.swing.JPanel();
        livrosCadastro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        redCircleLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        livrosDivideBar = new javax.swing.JPanel();
        livrosPesquisa = new javax.swing.JPanel();
        livrosPesquisaBar = new javax.swing.JPanel();
        livrosPesquisaLabel = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        livrosPorLabel = new javax.swing.JLabel();
        livrosPorComboBox = new javax.swing.JComboBox<>();
        livrosPesquisaLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        abaRanking = new javax.swing.JPanel();
        relatorioAtrasoPanel = new javax.swing.JPanel();
        relatorioAtrasoHeadPanel = new javax.swing.JPanel();
        relatorioAtrasoLabel = new javax.swing.JLabel();
        relatorioAtrasoTablePanel = new javax.swing.JPanel();
        relatorioAtrasoTabelaContent = new javax.swing.JScrollPane();
        relatorioAtrasoTabela = new javax.swing.JTable();
        menuBar = new javax.swing.JPanel();
        alunosActivePanel = new javax.swing.JPanel();
        alunosLabel = new javax.swing.JLabel();
        livrosActivePanel = new javax.swing.JPanel();
        livrosLabel = new javax.swing.JLabel();
        emprestimoActivePanel = new javax.swing.JPanel();
        emprestimoLabel = new javax.swing.JLabel();
        relatorioActivePanel = new javax.swing.JPanel();
        inMenuBarSpaceLabel = new javax.swing.JLabel();
        menuRightPanel = new javax.swing.JPanel();
        space = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setUndecorated(true);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        mainPanel.setBackground(new java.awt.Color(120, 133, 231));
        mainPanel.setLayout(new java.awt.GridBagLayout());

        programBar.setBackground(new java.awt.Color(111, 115, 204));
        programBar.setMaximumSize(new java.awt.Dimension(2147483647, 25));
        programBar.setPreferredSize(new java.awt.Dimension(633, 25));
        programBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                programBarMouseDragged(evt);
            }
        });
        programBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                programBarMousePressed(evt);
            }
        });
        programBar.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        programBar.add(titleBarSpaceLabel, gridBagConstraints);

        minemizeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        minemizeLabel.setForeground(new java.awt.Color(255, 255, 255));
        minemizeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/edu/anm/presenter/images/minimizeIcon.png"))); // NOI18N
        minemizeLabel.setMinimumSize(new java.awt.Dimension(25, 25));
        minemizeLabel.setPreferredSize(new java.awt.Dimension(25, 23));
        minemizeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minemizeLabelMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        programBar.add(minemizeLabel, gridBagConstraints);

        closeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        closeLabel.setForeground(new java.awt.Color(255, 255, 255));
        closeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/edu/anm/presenter/images/closeIcon.png"))); // NOI18N
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        programBar.add(closeLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        mainPanel.add(programBar, gridBagConstraints);

        titleBar.setBackground(new java.awt.Color(146, 199, 239));
        titleBar.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        titleBar.setMinimumSize(new java.awt.Dimension(240, 50));
        titleBar.setPreferredSize(new java.awt.Dimension(240, 50));
        titleBar.setLayout(new java.awt.GridBagLayout());

        menuIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/edu/anm/presenter/images/menuIcon.png"))); // NOI18N
        menuIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuIconMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 12, 5, 12);
        titleBar.add(menuIcon, gridBagConstraints);

        multimeiosLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        multimeiosLabel.setForeground(new java.awt.Color(255, 255, 255));
        multimeiosLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        multimeiosLabel.setText("Presenter");
        titleBar.add(multimeiosLabel, new java.awt.GridBagConstraints());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        titleBar.add(mainbarSpaceLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        mainPanel.add(titleBar, gridBagConstraints);

        contentPanel.setBackground(new java.awt.Color(120, 128, 175));
        contentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        abas.setMinimumSize(new java.awt.Dimension(900, 575));
        abas.setPreferredSize(new java.awt.Dimension(900, 575));

        abaEquipes.setBackground(new java.awt.Color(173, 211, 250));
        abaEquipes.setLayout(new java.awt.GridBagLayout());

        alunoCadastro.setBackground(new java.awt.Color(173, 211, 250));
        alunoCadastro.setForeground(new java.awt.Color(146, 199, 239));
        alunoCadastro.setMaximumSize(new java.awt.Dimension(2147483647, 600));
        alunoCadastro.setMinimumSize(new java.awt.Dimension(698, 300));
        alunoCadastro.setPreferredSize(new java.awt.Dimension(600, 300));
        alunoCadastro.setLayout(new java.awt.GridBagLayout());

        alunosNomeLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        alunosNomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        alunosNomeLabel.setText("Equipe:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 0);
        alunoCadastro.add(alunosNomeLabel, gridBagConstraints);

        alunosNomeTextField.setBackground(new java.awt.Color(146, 199, 239));
        alunosNomeTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        alunosNomeTextField.setForeground(new java.awt.Color(255, 255, 255));
        alunosNomeTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        alunosNomeTextField.setMinimumSize(new java.awt.Dimension(350, 30));
        alunosNomeTextField.setPreferredSize(new java.awt.Dimension(350, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 75, 25, 0);
        alunoCadastro.add(alunosNomeTextField, gridBagConstraints);

        alunosNomeLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        alunosNomeLabel1.setForeground(new java.awt.Color(255, 255, 255));
        alunosNomeLabel1.setText("Projeto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 0);
        alunoCadastro.add(alunosNomeLabel1, gridBagConstraints);

        alunosNomeTextField1.setBackground(new java.awt.Color(146, 199, 239));
        alunosNomeTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        alunosNomeTextField1.setForeground(new java.awt.Color(255, 255, 255));
        alunosNomeTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        alunosNomeTextField1.setMinimumSize(new java.awt.Dimension(350, 30));
        alunosNomeTextField1.setPreferredSize(new java.awt.Dimension(345, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 80, 25, 0);
        alunoCadastro.add(alunosNomeTextField1, gridBagConstraints);

        alunosTurmaLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        alunosTurmaLabel.setForeground(new java.awt.Color(255, 255, 255));
        alunosTurmaLabel.setText("Turma:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
        alunoCadastro.add(alunosTurmaLabel, gridBagConstraints);

        alunosTurmaComboBox.setBackground(new java.awt.Color(51, 51, 255));
        alunosTurmaComboBox.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        alunosTurmaComboBox.setForeground(new java.awt.Color(255, 255, 255));
        alunosTurmaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1º Administração", "1º Enfermagem", "1º Informática", "2º Administração", "2º Enfermagem", "2º Informática", "3º Administração", "3º Enfermagem", "3º Informática" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 75, 30, 0);
        alunoCadastro.add(alunosTurmaComboBox, gridBagConstraints);

        alunosNovoBotao.setBackground(new java.awt.Color(111, 135, 214));
        alunosNovoBotao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        alunosNovoBotao.setForeground(new java.awt.Color(255, 255, 255));
        alunosNovoBotao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alunosNovoBotao.setText("Novo");
        alunosNovoBotao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        alunosNovoBotao.setMaximumSize(new java.awt.Dimension(70, 32));
        alunosNovoBotao.setMinimumSize(new java.awt.Dimension(70, 32));
        alunosNovoBotao.setOpaque(true);
        alunosNovoBotao.setPreferredSize(new java.awt.Dimension(70, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        alunoCadastro.add(alunosNovoBotao, gridBagConstraints);

        alunosSalvarBotao.setBackground(new java.awt.Color(111, 135, 214));
        alunosSalvarBotao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        alunosSalvarBotao.setForeground(new java.awt.Color(255, 255, 255));
        alunosSalvarBotao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alunosSalvarBotao.setText("Salvar");
        alunosSalvarBotao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        alunosSalvarBotao.setMaximumSize(new java.awt.Dimension(70, 32));
        alunosSalvarBotao.setMinimumSize(new java.awt.Dimension(70, 32));
        alunosSalvarBotao.setOpaque(true);
        alunosSalvarBotao.setPreferredSize(new java.awt.Dimension(70, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 130, 0, 0);
        alunoCadastro.add(alunosSalvarBotao, gridBagConstraints);

        alunosEditarBotao.setBackground(new java.awt.Color(111, 135, 214));
        alunosEditarBotao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        alunosEditarBotao.setForeground(new java.awt.Color(255, 255, 255));
        alunosEditarBotao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alunosEditarBotao.setText("Editar");
        alunosEditarBotao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        alunosEditarBotao.setMaximumSize(new java.awt.Dimension(70, 32));
        alunosEditarBotao.setMinimumSize(new java.awt.Dimension(70, 32));
        alunosEditarBotao.setOpaque(true);
        alunosEditarBotao.setPreferredSize(new java.awt.Dimension(70, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 130);
        alunoCadastro.add(alunosEditarBotao, gridBagConstraints);

        alunosExcluirBotao.setBackground(new java.awt.Color(111, 135, 214));
        alunosExcluirBotao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        alunosExcluirBotao.setForeground(new java.awt.Color(255, 255, 255));
        alunosExcluirBotao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alunosExcluirBotao.setText("Excluir");
        alunosExcluirBotao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        alunosExcluirBotao.setMaximumSize(new java.awt.Dimension(70, 32));
        alunosExcluirBotao.setMinimumSize(new java.awt.Dimension(70, 32));
        alunosExcluirBotao.setOpaque(true);
        alunosExcluirBotao.setPreferredSize(new java.awt.Dimension(70, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        alunoCadastro.add(alunosExcluirBotao, gridBagConstraints);

        alunosNomeLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        alunosNomeLabel2.setForeground(new java.awt.Color(255, 255, 255));
        alunosNomeLabel2.setText("Aluno:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 25, 0);
        alunoCadastro.add(alunosNomeLabel2, gridBagConstraints);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(470, 160));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(470, 160));

        jList1.setBackground(new java.awt.Color(146, 199, 239));
        jList1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jList1.setForeground(new java.awt.Color(255, 255, 255));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setMaximumSize(new java.awt.Dimension(75, 135));
        jList1.setMinimumSize(new java.awt.Dimension(75, 135));
        jList1.setPreferredSize(new java.awt.Dimension(75, 135));
        jScrollPane1.setViewportView(jList1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        alunoCadastro.add(jScrollPane1, gridBagConstraints);

        alunosNomeTextField2.setBackground(new java.awt.Color(146, 199, 239));
        alunosNomeTextField2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        alunosNomeTextField2.setForeground(new java.awt.Color(255, 255, 255));
        alunosNomeTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        alunosNomeTextField2.setMinimumSize(new java.awt.Dimension(350, 30));
        alunosNomeTextField2.setPreferredSize(new java.awt.Dimension(350, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 100, 25, 0);
        alunoCadastro.add(alunosNomeTextField2, gridBagConstraints);

        alunosNovoBotao1.setBackground(new java.awt.Color(111, 135, 214));
        alunosNovoBotao1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        alunosNovoBotao1.setForeground(new java.awt.Color(255, 255, 255));
        alunosNovoBotao1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alunosNovoBotao1.setText("Adicionar");
        alunosNovoBotao1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        alunosNovoBotao1.setMinimumSize(new java.awt.Dimension(70, 32));
        alunosNovoBotao1.setOpaque(true);
        alunosNovoBotao1.setPreferredSize(new java.awt.Dimension(90, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 460, 25, 0);
        alunoCadastro.add(alunosNovoBotao1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        abaEquipes.add(alunoCadastro, gridBagConstraints);

        alunosDivideBar.setBackground(new java.awt.Color(255, 255, 255));
        alunosDivideBar.setMinimumSize(new java.awt.Dimension(10, 5));
        alunosDivideBar.setPreferredSize(new java.awt.Dimension(10, 5));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        abaEquipes.add(alunosDivideBar, gridBagConstraints);

        alunosPesquisaPanel.setBackground(new java.awt.Color(173, 211, 250));
        alunosPesquisaPanel.setLayout(new java.awt.GridBagLayout());

        alunosPesquisaBar.setBackground(new java.awt.Color(173, 211, 250));
        alunosPesquisaBar.setMinimumSize(new java.awt.Dimension(615, 90));
        alunosPesquisaBar.setPreferredSize(new java.awt.Dimension(615, 90));
        alunosPesquisaBar.setLayout(new java.awt.GridBagLayout());

        alunosPesquisaLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        alunosPesquisaLabel.setForeground(new java.awt.Color(255, 255, 255));
        alunosPesquisaLabel.setText("Pesquisa:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        alunosPesquisaBar.add(alunosPesquisaLabel, gridBagConstraints);

        alunosPesquisaTextField.setBackground(new java.awt.Color(146, 199, 239));
        alunosPesquisaTextField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        alunosPesquisaTextField.setForeground(new java.awt.Color(255, 255, 255));
        alunosPesquisaTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        alunosPesquisaTextField.setMinimumSize(new java.awt.Dimension(350, 35));
        alunosPesquisaTextField.setPreferredSize(new java.awt.Dimension(350, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 95, 10, 20);
        alunosPesquisaBar.add(alunosPesquisaTextField, gridBagConstraints);

        alunosPorLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        alunosPorLabel.setForeground(new java.awt.Color(255, 255, 255));
        alunosPorLabel.setText("Por:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 470, 10, 0);
        alunosPesquisaBar.add(alunosPorLabel, gridBagConstraints);

        alunosPorComboBox.setBackground(new java.awt.Color(51, 51, 255));
        alunosPorComboBox.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        alunosPorComboBox.setForeground(new java.awt.Color(255, 255, 255));
        alunosPorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Projeto", "Aluno" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 515, 10, 0);
        alunosPesquisaBar.add(alunosPorComboBox, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        alunosPesquisaPanel.add(alunosPesquisaBar, gridBagConstraints);

        alunosTabelaPanel.setBackground(new java.awt.Color(173, 211, 250));
        alunosTabelaPanel.setMinimumSize(new java.awt.Dimension(750, 402));
        alunosTabelaPanel.setPreferredSize(new java.awt.Dimension(750, 402));
        alunosTabelaPanel.setLayout(new java.awt.GridBagLayout());

        alunosTabelaContent.setForeground(new java.awt.Color(255, 255, 255));
        alunosTabelaContent.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        alunosTabelaContent.setMinimumSize(new java.awt.Dimension(900, 402));
        alunosTabelaContent.setPreferredSize(new java.awt.Dimension(900, 402));

        alunosTabela.setBackground(new java.awt.Color(146, 199, 239));
        alunosTabela.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        alunosTabela.setForeground(new java.awt.Color(255, 255, 255));
        alunosTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Projeto", "Turma", "Alunos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        alunosTabela.setToolTipText("\n");
        alunosTabela.setGridColor(new java.awt.Color(146, 199, 239));
        alunosTabela.setRowHeight(25);
        alunosTabela.setSelectionBackground(new java.awt.Color(173, 211, 250));
        alunosTabela.setShowGrid(false);
        alunosTabelaContent.setViewportView(alunosTabela);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        alunosTabelaPanel.add(alunosTabelaContent, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 1.0;
        alunosPesquisaPanel.add(alunosTabelaPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        abaEquipes.add(alunosPesquisaPanel, gridBagConstraints);

        abas.addTab("tab1", abaEquipes);

        abaTemporizador.setBackground(new java.awt.Color(173, 211, 250));
        abaTemporizador.setLayout(new java.awt.GridBagLayout());

        livrosCadastro.setBackground(new java.awt.Color(173, 211, 250));
        livrosCadastro.setMaximumSize(new java.awt.Dimension(2147483647, 325));
        livrosCadastro.setMinimumSize(new java.awt.Dimension(785, 325));
        livrosCadastro.setPreferredSize(new java.awt.Dimension(785, 200));
        livrosCadastro.setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/edu/anm/presenter/images/whiteCircle.png"))); // NOI18N
        livrosCadastro.add(jLabel1, new java.awt.GridBagConstraints());

        redCircleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/edu/anm/presenter/images/redCircle.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 3, 0, 0);
        livrosCadastro.add(redCircleLabel, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 85)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("00:00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        livrosCadastro.add(jLabel6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        abaTemporizador.add(livrosCadastro, gridBagConstraints);

        livrosDivideBar.setBackground(new java.awt.Color(255, 255, 255));
        livrosDivideBar.setMinimumSize(new java.awt.Dimension(10, 5));
        livrosDivideBar.setPreferredSize(new java.awt.Dimension(10, 5));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        abaTemporizador.add(livrosDivideBar, gridBagConstraints);

        livrosPesquisa.setBackground(new java.awt.Color(173, 211, 250));
        livrosPesquisa.setMaximumSize(new java.awt.Dimension(2147483647, 180));
        livrosPesquisa.setMinimumSize(new java.awt.Dimension(615, 180));
        livrosPesquisa.setPreferredSize(new java.awt.Dimension(615, 200));
        livrosPesquisa.setLayout(new java.awt.GridBagLayout());

        livrosPesquisaBar.setBackground(new java.awt.Color(173, 211, 250));
        livrosPesquisaBar.setMinimumSize(new java.awt.Dimension(615, 90));
        livrosPesquisaBar.setPreferredSize(new java.awt.Dimension(615, 90));
        livrosPesquisaBar.setLayout(new java.awt.GridBagLayout());

        livrosPesquisaLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        livrosPesquisaLabel.setForeground(new java.awt.Color(255, 255, 255));
        livrosPesquisaLabel.setText("Customizado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        livrosPesquisaBar.add(livrosPesquisaLabel, gridBagConstraints);

        jFormattedTextField1.setBackground(new java.awt.Color(146, 199, 239));
        jFormattedTextField1.setForeground(new java.awt.Color(255, 255, 255));
        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jFormattedTextField1.setPreferredSize(new java.awt.Dimension(85, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        livrosPesquisaBar.add(jFormattedTextField1, gridBagConstraints);

        livrosPorLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        livrosPorLabel.setForeground(new java.awt.Color(255, 255, 255));
        livrosPorLabel.setText("Tempo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        livrosPesquisaBar.add(livrosPorLabel, gridBagConstraints);

        livrosPorComboBox.setBackground(new java.awt.Color(51, 51, 255));
        livrosPorComboBox.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        livrosPorComboBox.setForeground(new java.awt.Color(255, 255, 255));
        livrosPorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 minutos", "10 minutos", "15 minutos", "20 minutos", "Customizado" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        livrosPesquisaBar.add(livrosPorComboBox, gridBagConstraints);

        livrosPesquisaLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        livrosPesquisaLabel1.setForeground(new java.awt.Color(255, 255, 255));
        livrosPesquisaLabel1.setText("minutos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 0, 0);
        livrosPesquisaBar.add(livrosPesquisaLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        livrosPesquisa.add(livrosPesquisaBar, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(173, 211, 250));
        jPanel1.setPreferredSize(new java.awt.Dimension(10, 90));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/edu/anm/presenter/images/playIcon.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 20, 10);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/edu/anm/presenter/images/pauseIcon.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 20, 10);
        jPanel1.add(jLabel3, gridBagConstraints);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/edu/anm/presenter/images/deleteIcon.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 20, 10);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gov/edu/anm/presenter/images/moreOneIcon.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 20, 10);
        jPanel1.add(jLabel5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        livrosPesquisa.add(jPanel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        abaTemporizador.add(livrosPesquisa, gridBagConstraints);

        abas.addTab("tab2", abaTemporizador);

        abaRanking.setBackground(new java.awt.Color(173, 211, 250));
        abaRanking.setLayout(new java.awt.GridBagLayout());

        relatorioAtrasoPanel.setBackground(new java.awt.Color(173, 211, 250));
        relatorioAtrasoPanel.setLayout(new java.awt.GridBagLayout());

        relatorioAtrasoHeadPanel.setBackground(new java.awt.Color(173, 211, 250));
        relatorioAtrasoHeadPanel.setMinimumSize(new java.awt.Dimension(10, 70));
        relatorioAtrasoHeadPanel.setPreferredSize(new java.awt.Dimension(10, 70));
        relatorioAtrasoHeadPanel.setLayout(new java.awt.GridBagLayout());

        relatorioAtrasoLabel.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        relatorioAtrasoLabel.setForeground(new java.awt.Color(255, 255, 255));
        relatorioAtrasoLabel.setText("Ranking da Competição:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 30, 0);
        relatorioAtrasoHeadPanel.add(relatorioAtrasoLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        relatorioAtrasoPanel.add(relatorioAtrasoHeadPanel, gridBagConstraints);

        relatorioAtrasoTablePanel.setBackground(new java.awt.Color(173, 211, 250));
        relatorioAtrasoTablePanel.setLayout(new java.awt.GridBagLayout());

        relatorioAtrasoTabelaContent.setMinimumSize(new java.awt.Dimension(800, 500));
        relatorioAtrasoTabelaContent.setPreferredSize(new java.awt.Dimension(1000, 500));

        relatorioAtrasoTabela.setBackground(new java.awt.Color(146, 199, 239));
        relatorioAtrasoTabela.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        relatorioAtrasoTabela.setForeground(new java.awt.Color(255, 255, 255));
        relatorioAtrasoTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Equipe", "Projeto", "Turma", "Alunos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        relatorioAtrasoTabela.setRowHeight(25);
        relatorioAtrasoTabelaContent.setViewportView(relatorioAtrasoTabela);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 20, 50);
        relatorioAtrasoTablePanel.add(relatorioAtrasoTabelaContent, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        relatorioAtrasoPanel.add(relatorioAtrasoTablePanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        abaRanking.add(relatorioAtrasoPanel, gridBagConstraints);

        abas.addTab("tab4", abaRanking);

        contentPanel.add(abas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -39, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        mainPanel.add(contentPanel, gridBagConstraints);

        menuBar.setBackground(new java.awt.Color(173, 211, 250));
        menuBar.setAlignmentX(0.0F);
        menuBar.setAlignmentY(0.0F);
        menuBar.setMaximumSize(new java.awt.Dimension(260, 32767));
        menuBar.setMinimumSize(new java.awt.Dimension(250, 536));
        menuBar.setPreferredSize(new java.awt.Dimension(250, 525));
        menuBar.setLayout(new java.awt.GridBagLayout());

        alunosActivePanel.setBackground(new java.awt.Color(173, 211, 250));
        alunosActivePanel.setMinimumSize(new java.awt.Dimension(5, 35));
        alunosActivePanel.setPreferredSize(new java.awt.Dimension(5, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        menuBar.add(alunosActivePanel, gridBagConstraints);

        alunosLabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        alunosLabel.setForeground(new java.awt.Color(255, 255, 255));
        alunosLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alunosLabel.setText("Cadastro de Equipes");
        alunosLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        alunosLabel.setPreferredSize(new java.awt.Dimension(183, 35));
        alunosLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alunosLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                alunosLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                alunosLabelMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 15, 0);
        menuBar.add(alunosLabel, gridBagConstraints);

        livrosActivePanel.setBackground(new java.awt.Color(173, 211, 250));
        livrosActivePanel.setMinimumSize(new java.awt.Dimension(5, 35));
        livrosActivePanel.setPreferredSize(new java.awt.Dimension(5, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        menuBar.add(livrosActivePanel, gridBagConstraints);

        livrosLabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        livrosLabel.setForeground(new java.awt.Color(255, 255, 255));
        livrosLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        livrosLabel.setText("Temporizador");
        livrosLabel.setToolTipText("");
        livrosLabel.setPreferredSize(new java.awt.Dimension(174, 35));
        livrosLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                livrosLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                livrosLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                livrosLabelMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        menuBar.add(livrosLabel, gridBagConstraints);

        emprestimoActivePanel.setBackground(new java.awt.Color(173, 211, 250));
        emprestimoActivePanel.setMinimumSize(new java.awt.Dimension(5, 35));
        emprestimoActivePanel.setPreferredSize(new java.awt.Dimension(5, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        menuBar.add(emprestimoActivePanel, gridBagConstraints);

        emprestimoLabel.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        emprestimoLabel.setForeground(new java.awt.Color(255, 255, 255));
        emprestimoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emprestimoLabel.setText("Ranking");
        emprestimoLabel.setPreferredSize(new java.awt.Dimension(113, 35));
        emprestimoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emprestimoLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                emprestimoLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                emprestimoLabelMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        menuBar.add(emprestimoLabel, gridBagConstraints);

        relatorioActivePanel.setBackground(new java.awt.Color(173, 211, 250));
        relatorioActivePanel.setMinimumSize(new java.awt.Dimension(5, 35));
        relatorioActivePanel.setPreferredSize(new java.awt.Dimension(5, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        menuBar.add(relatorioActivePanel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        menuBar.add(inMenuBarSpaceLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weighty = 1.0;
        mainPanel.add(menuBar, gridBagConstraints);

        menuRightPanel.setBackground(new java.awt.Color(120, 133, 231));
        menuRightPanel.setLayout(new java.awt.GridBagLayout());

        space.setMinimumSize(new java.awt.Dimension(250, 0));
        space.setPreferredSize(new java.awt.Dimension(250, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        menuRightPanel.add(space, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        mainPanel.add(menuRightPanel, gridBagConstraints);

        getContentPane().add(mainPanel);

        setSize(new java.awt.Dimension(893, 609));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minemizeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minemizeLabelMouseClicked
        //Botão minimizar
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minemizeLabelMouseClicked

    private void programBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_programBarMousePressed
    }//GEN-LAST:event_programBarMousePressed

    private void programBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_programBarMouseDragged
    }//GEN-LAST:event_programBarMouseDragged

    private void menuIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuIconMouseClicked
        //Botão abrir/fechar menu
        if (contentPanel.isVisible() == true) {

            contentPanel.setVisible(false);
            contentPanel.setEnabled(false);
            menuBar.setVisible(true);
            menuBar.setEnabled(true);
            menuRightPanel.setVisible(true);
            menuRightPanel.setEnabled(true);

        } else {

            contentPanel.setVisible(true);
            contentPanel.setEnabled(true);
            menuBar.setVisible(false);
            menuBar.setEnabled(false);
            menuRightPanel.setVisible(false);
            menuRightPanel.setEnabled(false);

        }

    }//GEN-LAST:event_menuIconMouseClicked

    //Animações de mouse enter/exit na escolha de abas no menu
    private void alunosLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alunosLabelMouseEntered
        alunosActivePanel.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_alunosLabelMouseEntered

    private void alunosLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alunosLabelMouseExited
        alunosActivePanel.setBackground(new Color(173, 211, 250));
    }//GEN-LAST:event_alunosLabelMouseExited

    private void livrosLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_livrosLabelMouseEntered
        livrosActivePanel.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_livrosLabelMouseEntered

    private void livrosLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_livrosLabelMouseExited
        livrosActivePanel.setBackground(new Color(173, 211, 250));
    }//GEN-LAST:event_livrosLabelMouseExited

    private void emprestimoLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emprestimoLabelMouseEntered
        emprestimoActivePanel.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_emprestimoLabelMouseEntered

    private void emprestimoLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emprestimoLabelMouseExited
        emprestimoActivePanel.setBackground(new Color(173, 211, 250));
    }//GEN-LAST:event_emprestimoLabelMouseExited

    //Botão exit
    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeLabelMouseClicked

    //Escolhas de aba no menu
    private void alunosLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alunosLabelMouseClicked
        abas.setSelectedIndex(0);
        contentPanel.setVisible(true);
        contentPanel.setEnabled(true);
        menuBar.setVisible(false);
        menuBar.setEnabled(false);
    }//GEN-LAST:event_alunosLabelMouseClicked

    private void livrosLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_livrosLabelMouseClicked
        abas.setSelectedIndex(1);
        contentPanel.setVisible(true);
        contentPanel.setEnabled(true);
        menuBar.setVisible(false);
        menuBar.setEnabled(false);
    }//GEN-LAST:event_livrosLabelMouseClicked

    private void emprestimoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emprestimoLabelMouseClicked
        abas.setSelectedIndex(2);
        contentPanel.setVisible(true);
        contentPanel.setEnabled(true);
        menuBar.setVisible(false);
        menuBar.setEnabled(false);
    }//GEN-LAST:event_emprestimoLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(presenterGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(presenterGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(presenterGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(presenterGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new presenterGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abaEquipes;
    private javax.swing.JPanel abaRanking;
    private javax.swing.JPanel abaTemporizador;
    private javax.swing.JTabbedPane abas;
    private javax.swing.JPanel alunoCadastro;
    private javax.swing.JPanel alunosActivePanel;
    private javax.swing.JPanel alunosDivideBar;
    private javax.swing.JLabel alunosEditarBotao;
    private javax.swing.JLabel alunosExcluirBotao;
    private javax.swing.JLabel alunosLabel;
    private javax.swing.JLabel alunosNomeLabel;
    private javax.swing.JLabel alunosNomeLabel1;
    private javax.swing.JLabel alunosNomeLabel2;
    private javax.swing.JTextField alunosNomeTextField;
    private javax.swing.JTextField alunosNomeTextField1;
    private javax.swing.JTextField alunosNomeTextField2;
    private javax.swing.JLabel alunosNovoBotao;
    private javax.swing.JLabel alunosNovoBotao1;
    private javax.swing.JPanel alunosPesquisaBar;
    private javax.swing.JLabel alunosPesquisaLabel;
    private javax.swing.JPanel alunosPesquisaPanel;
    private javax.swing.JTextField alunosPesquisaTextField;
    private javax.swing.JComboBox<String> alunosPorComboBox;
    private javax.swing.JLabel alunosPorLabel;
    private javax.swing.JLabel alunosSalvarBotao;
    private javax.swing.JTable alunosTabela;
    private javax.swing.JScrollPane alunosTabelaContent;
    private javax.swing.JPanel alunosTabelaPanel;
    private javax.swing.JComboBox<String> alunosTurmaComboBox;
    private javax.swing.JLabel alunosTurmaLabel;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel emprestimoActivePanel;
    private javax.swing.JLabel emprestimoLabel;
    private javax.swing.JLabel inMenuBarSpaceLabel;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel livrosActivePanel;
    private javax.swing.JPanel livrosCadastro;
    private javax.swing.JPanel livrosDivideBar;
    private javax.swing.JLabel livrosLabel;
    private javax.swing.JPanel livrosPesquisa;
    private javax.swing.JPanel livrosPesquisaBar;
    private javax.swing.JLabel livrosPesquisaLabel;
    private javax.swing.JLabel livrosPesquisaLabel1;
    private javax.swing.JComboBox<String> livrosPorComboBox;
    private javax.swing.JLabel livrosPorLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel mainbarSpaceLabel;
    private javax.swing.JPanel menuBar;
    private javax.swing.JLabel menuIcon;
    private javax.swing.JPanel menuRightPanel;
    private javax.swing.JLabel minemizeLabel;
    private javax.swing.JLabel multimeiosLabel;
    private javax.swing.JPanel programBar;
    private javax.swing.JLabel redCircleLabel;
    private javax.swing.JPanel relatorioActivePanel;
    private javax.swing.JPanel relatorioAtrasoHeadPanel;
    private javax.swing.JLabel relatorioAtrasoLabel;
    private javax.swing.JPanel relatorioAtrasoPanel;
    private javax.swing.JTable relatorioAtrasoTabela;
    private javax.swing.JScrollPane relatorioAtrasoTabelaContent;
    private javax.swing.JPanel relatorioAtrasoTablePanel;
    private javax.swing.JLabel space;
    private javax.swing.JPanel titleBar;
    private javax.swing.JLabel titleBarSpaceLabel;
    // End of variables declaration//GEN-END:variables
}
